#!/usr/bin/env bash
# This script configures the ufw firewall to block all incoming traffic except for ports 22, 80, and 443.

# Reset ufw to default state
echo "y" | sudo ufw reset

# Install ufw
sudo apt-get -y update
sudo apt-get -y install ufw

# Deny all incoming traffic by default and allow all outgoing
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow specific ports
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp

# Enable ufw
echo "y" | sudo ufw enable
