#!/usr/bin/env bash
# This script configures the ufw firewall to block all incoming traffic except for ports 22, 80, and 443.

# Install ufw
sudo apt-get -y update
sudo apt-get -y install ufw

# Deny all incoming traffic by default
sudo ufw default deny incoming

# Allow specific ports
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp

# Enable ufw
sudo ufw enable
