#!/usr/bin/env bash
# Configures a brand new Ubuntu machine to the requirements of 0-custom_http_response_header

# Update package lists
sudo apt-get -y update
# Install nginx
sudo apt-get -y install nginx

# Configure Nginx to add the X-Served-By header
sudo sed -i '/http {/a \        add_header X-Served-By $HOSTNAME;' /etc/nginx/nginx.conf

# Restart Nginx to apply the changes
sudo service nginx restart
