#!/usr/bin/env bash
# This script installs and configures HAProxy on a new Ubuntu machine.

# Update package lists
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy

# Enable HAProxy to be managed by an init script
echo "ENABLED=1" | sudo tee /etc/default/haproxy > /dev/null

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOT
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 34.198.248.145:80 check
    server web-02 54.89.38.100:80 check
EOT

# Restart HAProxy to apply the changes
sudo service haproxy restart
